"""add mortgage term field

Revision ID: 08da990a5e81
Revises: f7f9f1274e3c
Create Date: 2026-08-18 21:26:03.530326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08da990a5e81'
down_revision = 'f7f9f1274e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mortgage_term', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('mortgage_term')

    # ### end Alembic commands ###
