"""add annual rent field

Revision ID: 8d0e53bf0f8a
Revises: 484172869449
Create Date: 2026-08-04 23:18:45.359393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0e53bf0f8a'
down_revision = '484172869449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_rent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('annual_rent')

    # ### end Alembic commands ###
