"""add mortgage type field

Revision ID: c70e93d59cc7
Revises: 08da990a5e81
Create Date: 2026-08-19 19:11:09.417483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70e93d59cc7'
down_revision = '08da990a5e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mortgage_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('mortgage_type')

    # ### end Alembic commands ###
