"""add annual expenses field

Revision ID: f7f9f1274e3c
Revises: 421148315fca
Create Date: 2026-08-17 22:09:00.484908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f9f1274e3c'
down_revision = '421148315fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_expenses', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('annual_expenses')

    # ### end Alembic commands ###
