"""add mortgage balance field

Revision ID: ff284ff5761c
Revises: 8d0e53bf0f8a
Create Date: 2026-08-14 22:58:35.790441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff284ff5761c'
down_revision = '8d0e53bf0f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mortgage_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('mortgage_balance')

    # ### end Alembic commands ###
